config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens
  
  root "kittens#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.json { render json: @kittens }
    end
  end
  
  def new
    @kitten = Kitten.new
  end
  

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten successfully created"
      redirect_to @kitten
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end
  
  def show
    respond_to do |format|
      format.json { render json: @kitten }
    end
  end

  def edit
  end
  
  def update
      if @kitten.update(kitten_params)
        flash[:success] = "Kitten was successfully updated"
        redirect_to @kitten
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  def destroy
    if @kitten.destroy
      flash[:success] = 'Kitten was successfully deleted.'
      redirect_to kittens_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to kittens_url
    end
  end
  
  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_flash.html.erb
<% if flash[:success].present? %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% elsif flash[:error].present? %>
  <div class="alert alert-error">
    <%= flash[:error] %>
  </div>
<% end %>

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <br><br>
  <%= f.label :cuteness %>
  <%= f.select :cuteness, ['adorable', 'cute', 'precious'] %>
  <br><br>
  <%= f.label :softness %>
  <%= f.select :softness, ['silky', 'fluffy', 'cuddly'] %>
  <br><br>
  <%= f.submit "Create Kitten" %>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Kittens#edit</h1>
<%= render 'flash' %>
<%= render 'form'%>
<%= link_to 'Delete Kitten', kitten_path, data: { turbo_method: :delete } %>

app/views/kittens/index.html.erb
<h1>Kittens#index</h1>
<%= render 'flash' %>
<% if @kittens.empty? %>
  <p>No kittens</p>
<% else %>
  <ul>
    <% @kittens.each do |kitten| %>
      <li>
        Name: <%= kitten.name %> <br>
        Age: <%= kitten.age %>
        <br>
        <%= link_to 'Kitten details', kitten_url(kitten) %>
        <%= link_to 'delete kitten', kitten_url(kitten), data: { turbo_method: :delete } %>
      </li> <br>
    <% end %>
  </ul>
<% end %>

<%= link_to 'create kitten', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Kittens#new</h1>
  <%= render 'flash' %>
  <%= render 'form' %>

app/views/kittens/show.html.erb
<h1>Kittens#show</h1>
<%= render 'flash' %>
Name: <%= @kitten.name %> <br><br>
Age: <%= @kitten.age %> <br><br>
Cuteness: <%= @kitten.cuteness %> <br><br>
Softness: <%= @kitten.softness %> <br><br>
<%= link_to 'delete kitten', kitten_url(@kitten), data: { turbo_method: :delete } %>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>